# Generated by Django 5.1.2 on 2024-11-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('genre', models.CharField(choices=[('hr', 'Хоррор'), ('ac', 'Экшн'), ('fa', 'Фантастика'), ('sc', 'Научный')], max_length=255, verbose_name='Жанр')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration', models.CharField(max_length=255, verbose_name='Продолжительность')),
            ],
        ),
    ]
